name: build

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/build.yml

jobs:
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_OWNER: k1low
      IMAGE_NAME: centve
      # See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
      # ruby-build https://github.com/rbenv/ruby-build/commit/6c08c56d3aa0add92c60653744324e7cdb3b24c3
      # php-build
      PHP_BUILD_EXTRA_MAKE_ARGUMENTS: -j2
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.IMAGE_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (base)
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            RUBY_VERSIONS=
            PERL_VERSIONS=
            PHP_VERSIONS=
          pull: true
          push: ${{ github.ref == 'refs/heads/main' }}
          labels: |
            org.opencontainers.image.source=https://github.com/k1LoW/centve
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:base
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:7-base

      - name: Build and push (default)
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: ${{ github.ref == 'refs/heads/main' }}
          labels: |
            org.opencontainers.image.source=https://github.com/k1LoW/centve
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:default
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:7-default
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:latest
