name: check

on:
  push:

jobs:
  check-image:
    name: Check Docker image
    runs-on: ubuntu-latest
    container: ghcr.io/k1low/centve:latest
    steps:
      - name: Show installed versions
        run: |
          anyenv-init
          rbenv versions
          plenv versions
          phpenv versions

      - name: Set Ruby version
        run: rbenv global $(rbenv versions | tail -1)

      - name: Show current Ruby version
        run: ruby -v

      - name: Set Perl version
        run: plenv global $(plenv versions | tail -1)

      - name: Show current Perl version
        run: perl -v

      - name: Set PHP version
        run: phpenv global $(phpenv versions | tail -1)

      - name: Show current PHP version
        run: php -v
